### ISSUE TITLE
URL without base Error

### ISSUE THREAD

**Issue by Sammo98** [dovahcrow/tldextract-rs#12]
The following code returns a ```Err(RelativeUrlWithoutBase)``` error but mirrors that of those in the examples.

```
use tldextract::{TldExtractor, TldOption};

fn main() {
    let extractor = TldExtractor::new(TldOption::default());
    let test = extractor.extract("www.google.com");
    println!("{test:?}")
}
```

Apologies in advance if user error!

**Comment by dovahcrow** [comment]
The code works for me on my side:
```
    Finished dev [unoptimized + debuginfo] target(s) in 7.79s
     Running `target/debug/examples/test`
[2022-07-29T00:13:55Z DEBUG tldextract::cache::local] Trying using local cached TLD data
[2022-07-29T00:13:55Z DEBUG tldextract::cache::remote] Trying getting remote TLD data
Ok(TldResult { domain: Some("google"), subdomain: Some("www"), suffix: Some("com") })
```

**Comment by Sammo98** [comment]
Could I be missing a feature enabled in cargo.toml ?

**Comment by dovahcrow** [comment]
@Sammo98 I used the default feature

**Comment by Sammo98** [comment]
Thanks @dovahcrow, so just to clarify this is the correct set up:

```
//main.rs
use tldextract::{TldExtractor, TldOption};

fn main() {
    let extractor = TldExtractor::new(TldOption::default());
    let test = extractor.extract("www.google.com");
    println!("{test:?}")
}

//cargo.toml
[package]
name = "tld_test"
version = "0.1.0"
edition = "2021"

[dependencies]
tldextract = "0.5.1"

// tree
.
├── .gitignore
├── .tld_cache
├── Cargo.lock
├── Cargo.toml
└── src
    └── main.rs
```

If so, I'm still struggling to get it working, any ideas?

**Comment by dovahcrow** [comment]
@Sammo98 Can you try the git version? use `tldextract = { git = "https://github.com/dovahcrow/tldextract-rs" }` In your cargo.toml

**Comment by Sammo98** [comment]
@dovahcrow Thank you, this solved the problem! 
The error still occurs when using the crates.io version, but this works for me, thanks for the help.

P.S Love the crate, use the python package all the time.

**Comment by dovahcrow** [comment]
@Sammo98 Thanks for the confirmation! I'll release a new version to crates.io.
